### ISSUE TITLE
Boundary check in idxqry.C

### ISSUE THREAD

**Issue by anson304** [powturbo/TurboPFor#104]
Hello,

Sorry for asking so many questions, but I'm confused why a boundary check is not required for x[1] and y[1] in line 395 of idxqry.c.

Once the last block is reached, x[0] will point to the starting posting of the last block, and x[1] will be out of bounds.

This is the code for the intersection of two terms:
```unsigned *_x = (unsigned *)v[0].bp, *x_ = _x+v[0].bnum, *x = _x, *xd;
      unsigned *_y = (unsigned *)v[1].bp, *y_ = _y+v[1].bnum, *y = _y, *yd;
      _xd[0] = _yd[0] = UINT_MAX;
      for(;;) { unsigned x0 = x[0] == _xd[0], y0 = y[0] == _yd[0];
        if((x0?xd[0]:x[0]+1) <= y[1] && (y0?yd[0]+1:y[0]) <= x[1]) {
          if(!x0) xdnum = postdec(&v[0], x - _x, xd = _xd);
          if(!y0) ydnum = postdec(&v[1], y - _y, yd = _yd);
          unsigned _r = 0;
          INTERSECT(xd, _xd+xdnum, yd, _yd+ydnum);
          f_t += _r;                    STAT(_r?st_ovl++:st_noovl++);
        }
             if(y[1] < x[1]) { if(++y >= y_) break; }
        else if(x[1] < y[1]) { if(++x >= x_) break; }
        else if(++x == x_ || ++y == y_) break;                                  STAT(st_skip++);
      }```

**Comment by powturbo** [comment]
The _x & _y arrays are sorted and the value after the last value is set to INT_MAX in [line 181](https://github.com/powturbo/TurboPFor-Integer-Compression/blob/7b6921638f209b6446d2a399ff540d0f99b9519d/lib/idxqry.c#L181).
x & y are conditionally incremented and should stay within the boundaries.

**Comment by anson304** [comment]
Hi, correct me if I'm wrong, but x[0] and y[0] point to the skip list, but _x and _y point to the decoded arrays

**Comment by anson304** [comment]
Hi, correct me if I'm wrong, but doesn't line 81 modify the decoded array? x and y point to the skip list (the portion which contains the first DID of each block). When x is equal to x_ - 1, won't x[1] try to read the offset section of the skip list, which is invalid?

**Comment by powturbo** [comment]
The skip list is used for a direct access to the posting list with the docids. 
docids are always read from the posting list in the intersection.
The best way to check your asumption is to insert c-asserts in the coding.
I have no time to spend with debugging. These programs are provided only as a demo and must be expanded for a true query engine. 
The idea here is to demonstrate how you can drastically reduce the query time with the skip list providing direct access.
Only ~10-15% of the posting lists must be decoded using TurboPFor.
The query engine is scalable due to the share nothing multithreaded architecture.
