### ISSUE TITLE
Lack of #include's in vsimple

### ISSUE THREAD

**Issue by bellirodrigo2** [powturbo/TurboPFor#81]
I had to #include <string.h> in vsimple.c (it uses memcpy),
and I had to #include <stdint.h> in vsimple.h (to use uint_xx variables) in order to compile.

Am I missing something ?

**Comment by powturbo** [comment]
- Add "#include <string.h>" to avoid a warning because of memcpy use.
- "stdint.h" is already included in "conf.h" (needed by vsimple.c").
It will compile with gcc without warnings. There is one clang warning, that can be ignored.

There is nothing other to include. It will compile by simply typing "cc -c vsimple.c" (without passing any define macro).
It will compile also with other compilers.

**Comment by bellirodrigo2** [comment]
ok
