### ISSUE TITLE
Fastest Integer Decompression Algorithms?

### ISSUE THREAD

**Issue by anson304** [powturbo/TurboPFor#99]
Hello, in the README, it says that this package contains the fastest integer **compression** algorithms. Does this package also contain the fastest integer **decompression** algorithms? If not, do you know what is the current state of the art for fast decompression? (could you link github repo?)

**Comment by powturbo** [comment]
Well the topic is known as "Integer Compression" in academia and has to do with compression and decompression.
According to my tests, the TurboPFor is since the first version the fastest package for compression and decompression.
There is no other package that is faster with similar or better compression ratio.
This is valid for the bitpacking, TurboPfor, TurboByte,... functions. Additionally turbopfor works with arbitrary data,
other integer compression like fastpfor are crashing on large integer data. 
It is in general better to make the tests with your own data. IcApp has external libraries for comparison
(see also the benchmark in the issues).
There are also other criterias to consider when using integer compression.
For example the the block size in simd turbopfor is 128 integers, other IC packages (ex. FastPfor) can only work efficiently with large buffers.

**Comment by anson304** [comment]
Thanks for explaining :)
